export class Keycode {
  private static instance: Keycode;
  private constructor() {}

  static getInstance(): Keycode {
    if (!Keycode.instance) {
      Keycode.instance = new Keycode();
    }
    return Keycode.instance;
  }
  returnKeycodeForString = (keycodeString: string): any => {
    const catagories = [
      this.basic,
      this.basicExtended,
      this.internalCodes,
      this.layerKeys,
      this.audio,
      this.backLight,
      this.dynamicMacro,
      this.bootmagic,
      this.bluetooth,
      this.modTap,
      this.modPress,
    ];
    const cleanedKeycode = keycodeString
      .replace("(", "")
      .replace(")", "")
      .replace(",", "")
      .replace("KC_TRNS", "");
    for (const catagory of catagories) {
      if (catagory[cleanedKeycode]) {
        return catagory[cleanedKeycode];
      } else {
        return this.basic.KC_TRNS;
      }
    }
  };

  basic: any = {
    KC_NO: { code: "KC_NO", title: "KC_NO", description: "", webKeycode: "" },
    KC_TRNS: {
      code: "KC_TRNS",
      title: "KC_TRNS",
      description: "",
      webKeycode: "",
    },
    KC_A: { code: "KC_A", title: "A", description: "", webKeycode: "" },
    KC_B: { code: "KC_B", title: "B", description: "", webKeycode: "" },
    KC_C: { code: "KC_C", title: "C", description: "", webKeycode: "" },
    KC_D: { code: "KC_D", title: "D", description: "", webKeycode: "" },
    KC_E: { code: "KC_E", title: "E", description: "", webKeycode: "" },
    KC_F: { code: "KC_F", title: "F", description: "", webKeycode: "" },
    KC_G: { code: "KC_G", title: "G", description: "", webKeycode: "" },
    KC_H: { code: "KC_H", title: "H", descripkion: "", webKeycode: "" },
    KC_I: { code: "KC_I", title: "I", description: "", webKeycode: "" },
    KC_J: { code: "KC_J", title: "J", description: "", webKeycode: "" },
    KC_K: { code: "KC_K", title: "K", description: "", webKeycode: "" },
    KC_L: { code: "KC_L", title: "L", description: "", webKeycode: "" },
    KC_M: { code: "KC_M", title: "M", description: "", webKeycode: "" },
    KC_N: { code: "KC_N", title: "N", description: "", webKeycode: "" },
    KC_O: { code: "KC_O", title: "O", description: "", webKeycode: "" },
    KC_P: { code: "KC_P", title: "P", description: "", webKeycode: "" },
    KC_Q: { code: "KC_Q", title: "Q", description: "", webKeycode: "" },
    KC_R: { code: "KC_R", title: "R", description: "", webKeycode: "" },
    KC_S: { code: "KC_S", title: "S", description: "", webKeycode: "" },
    KC_T: { code: "KC_T", title: "T", description: "", webKeycode: "" },
    KC_U: { code: "KC_U", title: "U", description: "", webKeycode: "" },
    KC_V: { code: "KC_V", title: "V", description: "", webKeycode: "" },
    KC_W: { code: "KC_W", title: "W", description: "", webKeycode: "" },
    KC_X: { code: "KC_X", title: "X", description: "", webKeycode: "" },
    KC_Y: { code: "KC_Y", title: "Y", description: "", webKeycode: "" },
    KC_Z: { code: "KC_Z", title: "Z", description: "", webKeycode: "" },
    KC_1: { code: "KC_1", title: "1 !", description: "", webKeycode: "" },
    KC_2: { code: "KC_2", title: "2 @", description: "", webKeycode: "" },
    KC_3: { code: "KC_3", title: "3 #", description: "", webKeycode: "" },
    KC_4: { code: "KC_4", title: "4 $", description: "", webKeycode: "" },
    KC_5: { code: "KC_5", title: "5 %", description: "", webKeycode: "" },
    KC_6: { code: "KC_6", title: "6 ^", description: "", webKeycode: "" },
    KC_7: { code: "KC_7", title: "7 &", description: "", webKeycode: "" },
    KC_8: { code: "KC_8", title: "8 *", description: "", webKeycode: "" },
    KC_9: { code: "KC_9", title: "9 (", description: "", webKeycode: "" },
    KC_0: { code: "KC_0", title: "0 )", description: "", webKeycode: "" },
    KC_ENTER: {
      code: "KC_ENTER",
      title: "enter",
      description: "",
      webKeycode: "",
    },
    KC_ESCAPE: {
      code: "KC_ESCAPE",
      title: "escape",
      description: "",
      webKeycode: "",
    },
    KC_BSPACE: {
      code: "KC_BSPACE",
      title: "backspace",
      description: "",
      webKeycode: "",
    },
    KC_TAB: { code: "KC_TAB", title: "tab", description: "", webKeycode: "" },
    KC_SPACE: {
      code: "KC_SPACE",
      title: "Space",
      description: "",
      webKeycode: "",
    },
    KC_MINUS: {
      code: "KC_MINUS",
      title: "_ -",
      description: "",
      webKeycode: "",
    },
    KC_EQUAL: {
      code: "KC_EQUAL",
      title: "= +",
      description: "",
      webKeycode: "",
    },
    KC_LBRACKET: {
      code: "KC_LBRACKET",
      title: "",
      description: "",
      webKeycode: "",
    },
    KC_RBRACKET: {
      code: "KC_RBRACKET",
      title: "",
      description: "",
      webKeycode: "",
    },
    KC_BSLASH: {
      code: "KC_BSLASH",
      title: "",
      description: "",
      webKeycode: "",
    },
    KC_NONUS_HASH: {
      code: "KC_NONUS_HASH",
      title: "",
      description: "",
      webKeycode: "",
    },
    KC_SCOLON: {
      code: "KC_SCOLON",
      title: "",
      description: "",
      webKeycode: "",
    },
    KC_QUOTE: { code: "KC_QUOTE", title: "", description: "", webKeycode: "" },
    KC_GRAVE: { code: "KC_GRAVE", title: "", description: "", webKeycode: "" },
    KC_COMMA: { code: "KC_COMMA", title: "", description: "", webKeycode: "" },
    KC_DOT: { code: "KC_DOT", title: "", description: "", webKeycode: "" },
    KC_SLASH: { code: "KC_SLASH", title: "", description: "", webKeycode: "" },
    KC_CAPSLOCK: {
      code: "KC_CAPSLOCK",
      title: "",
      description: "",
      webKeycode: "",
    },
    KC_F1: { code: "KC_F1", title: "", description: "", webKeycode: "" },
    KC_F2: { code: "KC_F2", title: "", description: "", webKeycode: "" },
    KC_F3: { code: "KC_F3", title: "", description: "", webKeycode: "" },
    KC_F4: { code: "KC_F4", title: "", description: "", webKeycode: "" },
    KC_F5: { code: "KC_F5", title: "", description: "", webKeycode: "" },
    KC_F6: { code: "KC_F6", title: "", description: "", webKeycode: "" },
    KC_F7: { code: "KC_F7", title: "", description: "", webKeycode: "" },
    KC_F8: { code: "KC_F8", title: "", description: "", webKeycode: "" },
    KC_F9: { code: "KC_F9", title: "", description: "", webKeycode: "" },
    KC_F10: { code: "KC_F10", title: "", description: "", webKeycode: "" },
    KC_F11: { code: "KC_F11", title: "", description: "", webKeycode: "" },
    KC_F12: { code: "KC_F12", title: "", description: "", webKeycode: "" },
    KC_LCTRL: { code: "KC_LCTRL", title: "", description: "", webKeycode: "" },
    KC_LSHIFT: {
      code: "KC_LSHIFT",
      title: "",
      description: "",
      webKeycode: "",
    },
    KC_LALT: { code: "KC_LALT", title: "", description: "", webKeycode: "" },
    KC_LGUI: { code: "KC_LGUI", title: "", description: "", webKeycode: "" },
    KC_RCTRL: { code: "KC_RCTRL", title: "", description: "", webKeycode: "" },
    KC_RSHIFT: {
      code: "KC_RSHIFT",
      title: "",
      description: "",
      webKeycode: "",
    },
    KC_RALT: { code: "KC_RALT", title: "", description: "", webKeycode: "" },
    KC_RGUI: { code: "KC_RGUI", title: "", description: "", webKeycode: "" },
    KC_PSCREEN: {
      code: "KC_PSCREEN",
      title: "",
      description: "",
      webKeycode: "",
    },
    KC_SCROLLLOCK: {
      code: "KC_SCROLLLOCK",
      title: "",
      description: "",
      webKeycode: "",
    },
    KC_PAUSE: { code: "KC_PAUSE", title: "", description: "", webKeycode: "" },
    KC_INSERT: {
      code: "KC_INSERT",
      title: "",
      description: "",
      webKeycode: "",
    },
    KC_HOME: { code: "KC_HOME", title: "", description: "", webKeycode: "" },
    KC_PGUP: { code: "KC_PGUP", title: "", description: "", webKeycode: "" },
    KC_DELETE: {
      code: "KC_DELETE",
      title: "",
      description: "",
      webKeycode: "",
    },
    KC_END: { code: "KC_END", title: "", description: "", webKeycode: "" },
    KC_PGDOWN: {
      code: "KC_PGDOWN",
      title: "",
      description: "",
      webKeycode: "",
    },
    KC_RIGHT: { code: "KC_RIGHT", title: "", description: "", webKeycode: "" },
    KC_RGHT: { code: "KC_RGHT", title: "", description: "", webKeycode: "" },
    KC_LEFT: { code: "KC_LEFT", title: "", description: "", webKeycode: "" },
    KC_DOWN: { code: "KC_DOWN", title: "", description: "", webKeycode: "" },
    KC_UP: { code: "KC_UP", title: "", description: "", webKeycode: "" },
    KC_NUMLOCK: {
      code: "KC_NUMLOCK",
      title: "",
      description: "",
      webKeycode: "",
    },
    KC_KP_SLASH: {
      code: "KC_KP_SLASH",
      title: "",
      description: "",
      webKeycode: "",
    },
    KC_KP_ASTERISK: {
      code: "KC_KP_ASTERISK",
      title: "",
      description: "",
      webKeycode: "",
    },
    KC_KP_MINUS: {
      code: "KC_KP_MINUS",
      title: "",
      description: "",
      webKeycode: "",
    },
    KC_KP_PLUS: {
      code: "KC_KP_PLUS",
      title: "",
      description: "",
      webKeycode: "",
    },
    KC_KP_ENTER: {
      code: "KC_KP_ENTER",
      title: "",
      description: "",
      webKeycode: "",
    },
    KC_P1: { code: "KC_P1", title: "", description: "", webKeycode: "" },
    KC_P2: { code: "KC_P2", title: "", description: "", webKeycode: "" },
    KC_P3: { code: "KC_P3", title: "", description: "", webKeycode: "" },
    KC_P4: { code: "KC_P4", title: "", description: "", webKeycode: "" },
    KC_P5: { code: "KC_P5", title: "", description: "", webKeycode: "" },
    KC_P6: { code: "KC_P6", title: "", description: "", webKeycode: "" },
    KC_P7: { code: "KC_P7", title: "", description: "", webKeycode: "" },
    KC_P8: { code: "KC_P8", title: "", description: "", webKeycode: "" },
    KC_P9: { code: "KC_P9", title: "", description: "", webKeycode: "" },
    KC_P0: { code: "KC_P0", title: "", description: "", webKeycode: "" },
    KC_KP_DOT: {
      code: "KC_KP_DOT",
      title: "",
      description: "",
      webKeycode: "",
    },
    KC_NONUS_BSLASH: {
      code: "KC_NONUS_BSLASH",
      title: "",
      description: "",
      webKeycode: "",
    },
    KC_APPLICATION: {
      code: "KC_APPLICATION",
      title: "",
      description: "",
      webKeycode: "",
    },
    KC_POWER: { code: "KC_POWER", title: "", description: "", webKeycode: "" },
    KC_KP_EQUAL: {
      code: "KC_KP_EQUAL",
      title: "",
      description: "",
      webKeycode: "",
    },
    KC_F13: { code: "KC_F13", title: "", description: "", webKeycode: "" },
    KC_F14: { code: "KC_F14", title: "", description: "", webKeycode: "" },
    KC_F15: { code: "KC_F15", title: "", description: "", webKeycode: "" },
    KC_F16: { code: "KC_F16", title: "", description: "", webKeycode: "" },
    KC_F17: { code: "KC_F17", title: "", description: "", webKeycode: "" },
    KC_F18: { code: "KC_F18", title: "", description: "", webKeycode: "" },
    KC_F19: { code: "KC_F19", title: "", description: "", webKeycode: "" },
    KC_F20: { code: "KC_F20", title: "", description: "", webKeycode: "" },
    KC_F21: { code: "KC_F21", title: "", description: "", webKeycode: "" },
    KC_F22: { code: "KC_F22", title: "", description: "", webKeycode: "" },
    KC_F23: { code: "KC_F23", title: "", description: "", webKeycode: "" },
    KC_F24: { code: "KC_F24", title: "", description: "", webKeycode: "" },
  };

  basicExtended: any = {
    KC_EXECUTE: {
      code: "KC_EXECUTE",
      title: "",
      description: "",
      webKeycode: "",
    },
    KC_HELP: { code: "KC_HELP", title: "", description: "", webKeycode: "" },
    KC_MENU: { code: "KC_MENU", title: "", description: "", webKeycode: "" },
    KC_SELECT: {
      code: "KC_SELECT",
      title: "",
      description: "",
      webKeycode: "",
    },
    KC_STOP: { code: "KC_STOP", title: "", description: "", webKeycode: "" },
    KC_AGAIN: { code: "KC_AGAIN", title: "", description: "", webKeycode: "" },
    KC_UNDO: { code: "KC_UNDO", title: "", description: "", webKeycode: "" },
    KC_CUT: { code: "KC_CUT", title: "", description: "", webKeycode: "" },
    KC_COPY: { code: "KC_COPY", title: "", description: "", webKeycode: "" },
    KC_PASTE: { code: "KC_PASTE", title: "", description: "", webKeycode: "" },
    KC_FIND: { code: "KC_FIND", title: "", description: "", webKeycode: "" },
    KC__MUTE: { code: "KC__MUTE", title: "", description: "", webKeycode: "" },
    KC__VOLUP: {
      code: "KC__VOLUP",
      title: "",
      description: "",
      webKeycode: "",
    },
    KC__VOLDOWN: {
      code: "KC__VOLDOWN",
      title: "",
      description: "",
      webKeycode: "",
    },
    KC_LOCKING_CAPS: {
      code: "KC_LOCKING_CAPS",
      title: "",
      description: "",
      webKeycode: "",
    },
    KC_LOCKING_NUM: {
      code: "KC_LOCKING_NUM",
      title: "",
      description: "",
      webKeycode: "",
    },
    KC_LOCKING_SCROLL: {
      code: "KC_LOCKING_SCROLL",
      title: "",
      description: "",
      webKeycode: "",
    },
    KC_KP_COMMA: {
      code: "KC_KP_COMMA",
      title: "",
      description: "",
      webKeycode: "",
    },
    KC_KP_EQUAL_AS400: {
      code: "KC_KP_EQUAL_AS400",
      title: "",
      description: "",
      webKeycode: "",
    },
    KC_INT1: { code: "KC_INT1", title: "", description: "" },
    KC_INT2: { code: "KC_INT2", title: "", description: "" },
    KC_INT3: { code: "KC_INT3", title: "", description: "" },
    KC_INT4: { code: "KC_INT4", title: "", description: "" },
    KC_INT5: { code: "KC_INT5", title: "", description: "" },
    KC_INT6: { code: "KC_INT6", title: "", description: "" },
    KC_INT7: { code: "KC_INT7", title: "", description: "" },
    KC_INT8: { code: "KC_INT8", title: "", description: "" },
    KC_INT9: { code: "KC_INT9", title: "", description: "" },
    KC_LANG1: { code: "KC_LANG1", title: "", description: "" },
    KC_LANG2: { code: "KC_LANG2", title: "", description: "" },
    KC_LANG3: { code: "KC_LANG3", title: "", description: "" },
    KC_LANG4: { code: "KC_LANG4", title: "", description: "" },
    KC_LANG5: { code: "KC_LANG5", title: "", description: "" },
    KC_LANG6: { code: "KC_LANG6", title: "", description: "" },
    KC_LANG7: { code: "KC_LANG7", title: "", description: "" },
    KC_LANG8: { code: "KC_LANG8", title: "", description: "" },
    KC_LANG9: { code: "KC_LANG9", title: "", description: "" },
    KC_ALT_ERASE: { code: "KC_ALT_ERASE", title: "", description: "" },
    KC_SYSREQ: { code: "KC_SYSREQ", title: "", description: "" },
    KC_CANCEL: { code: "KC_CANCEL", title: "", description: "" },
    KC_CLEAR: { code: "KC_CLEAR", title: "", description: "" },
    KC_PRIOR: { code: "KC_PRIOR", title: "", description: "" },
    KC_RETURN: { code: "KC_RETURN", title: "", description: "" },
    KC_SEPARATOR: { code: "KC_SEPARATOR", title: "", description: "" },
    KC_OUT: { code: "KC_OUT", title: "", description: "" },
    KC_OPER: { code: "KC_OPER", title: "", description: "" },
    KC_CLEAR_AGAIN: { code: "KC_CLEAR_AGAIN", title: "", description: "" },
    KC_CRSEL: { code: "KC_CRSEL", title: "", description: "" },
    KC_EXSEL: { code: "KC_EXSEL", title: "", description: "" },
    KC_SYSTEM_POWER: { code: "KC_SYSTEM_POWER", title: "", description: "" },
    KC_SYSTEM_SLEEP: { code: "KC_SYSTEM_SLEEP", title: "", description: "" },
    KC_SYSTEM_WAKE: { code: "KC_SYSTEM_WAKE", title: "", description: "" },
    KC_AUDIO_MUTE: { code: "KC_AUDIO_MUTE", title: "", description: "" },
    KC_AUDIO_VOL_UP: { code: "KC_AUDIO_VOL_UP", title: "", description: "" },
    KC_AUDIO_VOL_DOWN: {
      code: "KC_AUDIO_VOL_DOWN",
      title: "",
      description: "",
    },
    KC_MEDIA_NEXT_TRACK: {
      code: "KC_MEDIA_NEXT_TRACK",
      title: "",
      description: "",
    },
    KC_MEDIA_PREV_TRACK: {
      code: "KC_MEDIA_PREV_TRACK",
      title: "",
      description: "",
    },
    KC_MEDIA_STOP: { code: "KC_MEDIA_STOP", title: "", description: "" },
    KC_MEDIA_PLAY_PAUSE: {
      code: "KC_MEDIA_PLAY_PAUSE",
      title: "",
      description: "",
    },
    KC_MEDIA_SELECT: { code: "KC_MEDIA_SELECT", title: "", description: "" },
    KC_MEDIA_EJECT: { code: "KC_MEDIA_EJECT", title: "", description: "" },
    KC_MAIL: { code: "KC_MAIL", title: "", description: "" },
    KC_CALCULATOR: { code: "KC_CALCULATOR", title: "", description: "" },
    KC_MY_COMPUTER: { code: "KC_MY_COMPUTER", title: "", description: "" },
    KC_WWW_SEARCH: { code: "KC_WWW_SEARCH", title: "", description: "" },
    KC_WWW_HOME: { code: "KC_WWW_HOME", title: "", description: "" },
    KC_WWW_BACK: { code: "KC_WWW_BACK", title: "", description: "" },
    KC_WWW_FORWARD: { code: "KC_WWW_FORWARD", title: "", description: "" },
    KC_WWW_STOP: { code: "KC_WWW_STOP", title: "", description: "" },
    KC_WWW_REFRESH: { code: "KC_WWW_REFRESH", title: "", description: "" },
    KC_WWW_FAVORITES: { code: "KC_WWW_FAVORITES", title: "", description: "" },
    KC_MEDIA_FAST_FORWARD: {
      code: "KC_MEDIA_FAST_FORWARD",
      title: "",
      description: "",
    },
    KC_MEDIA_REWIND: { code: "KC_MEDIA_REWIND", title: "", description: "" },
    KC_BRIGHTNESS_UP: { code: "KC_BRIGHTNESS_UP", title: "", description: "" },
    KC_BRIGHTNESS_DOWN: {
      code: "KC_BRIGHTNESS_DOWN",
      title: "",
      description: "",
    },
  };
  internalCodes: any = {
    RESET: { code: "RESET", title: "", description: "" },
    DEBUG: { code: "DEBUG", title: "", description: "" },
    EEPROM_RESET: { code: "EEPROM_RESET", title: "", description: "" },
  };
  audio: any = {
    AU_ON: { code: "AU_ON", title: "", description: "" },
    AU_OFF: { code: "AU_OFF", title: "", description: "" },
    AU_TOG: { code: "AU_TOG", title: "", description: "" },
    CLICKY_TOGGLE: { code: "CLICKY_TOGGLE", title: "", description: "" },
    CLICKY_UP: { code: "CLICKY_UP", title: "", description: "" },
    CLICKY_DOWN: { code: "CLICKY_DOWN", title: "", description: "" },
    CLICKY_RESET: { code: "CLICKY_RESET", title: "", description: "" },
    MU_ON: { code: "MU_ON", title: "", description: "" },
    MU_OFF: { code: "MU_OFF", title: "", description: "" },
    MU_TOG: { code: "MU_TOG", title: "", description: "" },
    MU_MOD: { code: "MU_MOD", title: "", description: "" },
  };
  backLight: any = {
    BL_TOGG: { code: "BL_TOGG", title: "", description: "" },
    BL_STEP: { code: "BL_STEP", title: "", description: "" },
    BL_ON: { code: "BL_ON", title: "", description: "" },
    BL_OFF: { code: "BL_OFF", title: "", description: "" },
    BL_INC: { code: "BL_INC", title: "", description: "" },
    BL_DEC: { code: "BL_DEC", title: "", description: "" },
    BL_BRTG: { code: "BL_BRTG", title: "", description: "" },
  };
  bootmagic: any = {
    CL_SWAP: { code: "CL_SWAP", title: "", description: "" },
    CL_NORM: { code: "CL_NORM", title: "", description: "" },
    CL_CTRL: { code: "CL_CTRL", title: "", description: "" },
    CL_CAPS: { code: "CL_CAPS", title: "", description: "" },
    LCG_SWP: { code: "LCG_SWP", title: "", description: "" },
    LCG_NRM: { code: "LCG_NRM", title: "", description: "" },
    RCG_SWP: { code: "RCG_SWP", title: "", description: "" },
    RCG_NRM: { code: "RCG_NRM", title: "", description: "" },
    CG_SWAP: { code: "CG_SWAP", title: "", description: "" },
    CG_NORM: { code: "CG_NORM", title: "", description: "" },
    CG_TOGG: { code: "CG_TOGG", title: "", description: "" },
    LAG_SWP: { code: "LAG_SWP", title: "", description: "" },
    LAG_NRM: { code: "LAG_NRM", title: "", description: "" },
    RAG_SWP: { code: "RAG_SWP", title: "", description: "" },
    RAG_NRM: { code: "RAG_NRM", title: "", description: "" },
    AG_SWAP: { code: "AG_SWAP", title: "", description: "" },
    AG_NORM: { code: "AG_NORM", title: "", description: "" },
    AG_TOGG: { code: "AG_TOGG", title: "", description: "" },
    GUI_OFF: { code: "GUI_OFF", title: "", description: "" },
    GUI_ON: { code: "GUI_ON", title: "", description: "" },
    GE_SWAP: { code: "GE_SWAP", title: "", description: "" },
    GE_NORM: { code: "GE_NORM", title: "", description: "" },
    BS_SWAP: { code: "BS_SWAP", title: "", description: "" },
    BS_NORM: { code: "BS_NORM", title: "", description: "" },
    NK_ON: { code: "NK_ON", title: "", description: "" },
    NK_OFF: { code: "NK_OFF", title: "", description: "" },
    NK_TOGG: { code: "NK_TOGG", title: "", description: "" },
    EH_LEFT: { code: "EH_LEFT", title: "", description: "" },
    EH_RGHT: { code: "EH_RGHT", title: "", description: "" },
  };
  bluetooth: any = {
    OUT_AUTO: { code: "OUT_AUTO", title: "", description: "" },
    OUT_USB: { code: "OUT_USB", title: "", description: "" },
    OUT_BT: { code: "OUT_BT", title: "", description: "" },
  };
  dynamicMacro: any = {
    DM_REC1: { code: "DM_REC1", title: "", description: "" },
    DM_REC2: { code: "DM_REC2", title: "", description: "" },
    DM_PLY1: { code: "DM_PLY1", title: "", description: "" },
    DM_PLY2: { code: "DM_PLY2", title: "", description: "" },
    DM_RSTP: { code: "DM_RSTP", title: "", description: "" },
    GRAVE_ESC: { code: "GRAVE_ESC", title: "", description: "" },
    KC_GESC: { code: "KC_GESC", title: "", description: "" },
    KC_LOCK: { code: "KC_LOCK", title: "", description: "" },
  };
  layerKeys: any = {
    DF0: { code: "DF(0)", title: "DF 0", description: "" },
    DF1: { code: "DF(1)", title: "DF 1", description: "" },
    DF2: { code: "DF(2)", title: "DF 2", description: "" },
    DF3: { code: "DF(3)", title: "DF 3", description: "" },
    DF4: { code: "DF(4)", title: "DF 4", description: "" },
    DF5: { code: "DF(5)", title: "DF 5", description: "" },
    DF6: { code: "DF(6)", title: "DF 6", description: "" },
    MO0: { code: "MO(0)", title: "MO 0", description: "" },
    MO1: { code: "MO(1)", title: "MO 1", description: "" },
    MO2: { code: "MO(2)", title: "MO 2", description: "" },
    MO3: { code: "MO(3)", title: "MO 3", description: "" },
    MO4: { code: "MO(4)", title: "MO 4", description: "" },
    MO5: { code: "MO(5)", title: "MO 5", description: "" },
    MO6: { code: "MO(6)", title: "MO 6", description: "" },
    TO0: { code: "TO(0)", title: "TO 0", description: "" },
    TO1: { code: "TO(1)", title: "TO 1", description: "" },
    TO2: { code: "TO(2)", title: "TO 2", description: "" },
    TO3: { code: "TO(3)", title: "TO 3", description: "" },
    TO4: { code: "TO(4)", title: "TO 4", description: "" },
    TO5: { code: "TO(5)", title: "TO 5", description: "" },
    TO6: { code: "TO(6)", title: "TO 6", description: "" },
    TG0: { code: "TG(0)", title: "TG 0", description: "" },
    TG1: { code: "TG(1)", title: "TG 1", description: "" },
    TG2: { code: "TG(2)", title: "TG 2", description: "" },
    TG3: { code: "TG(3)", title: "TG 3", description: "" },
    TG4: { code: "TG(4)", title: "TG 4", description: "" },
    TG5: { code: "TG(5)", title: "TG 5", description: "" },
    TG6: { code: "TG(6)", title: "TG 6", description: "" },
    TT0: { code: "TT(0)", title: "TT 0", description: "" },
    TT1: { code: "TT(1)", title: "TT 1", description: "" },
    TT2: { code: "TT(2)", title: "TT 2", description: "" },
    TT3: { code: "TT(3)", title: "TT 3", description: "" },
    TT4: { code: "TT(4)", title: "TT 4", description: "" },
    TT5: { code: "TT(5)", title: "TT 5", description: "" },
    TT6: { code: "TT(6)", title: "TT 6", description: "" },
    OSL0: { code: "OSL(0)", title: "OSL 0", description: "" },
    OSL1: { code: "OSL(1)", title: "OSL 1", description: "" },
    OSL2: { code: "OSL(2)", title: "OSL 2", description: "" },
    OSL3: { code: "OSL(3)", title: "OSL 3", description: "" },
    OSL4: { code: "OSL(4)", title: "OSL 4", description: "" },
    OSL5: { code: "OSL(5)", title: "OSL 5", description: "" },
    OSL6: { code: "OSL(6)", title: "OSL 6", description: "" },
    LM0: { code: "LM(0,KC_TRNS)", title: "LM 0 KC", description: "" },
    LM1: { code: "LM(1,KC_TRNS)", title: "LM 1 KC", description: "" },
    LM2: { code: "LM(2,KC_TRNS)", title: "LM 2 KC", description: "" },
    LM3: { code: "LM(3,KC_TRNS)", title: "LM 3 KC", description: "" },
    LM4: { code: "LM(4,KC_TRNS)", title: "LM 4 KC", description: "" },
    LM5: { code: "LM(5,KC_TRNS)", title: "LM 5 KC", description: "" },
    LM6: { code: "LM(6,KC_TRNS)", title: "LM 6 KC", description: "" },
    LT0: { code: "LT(0,KC_TRNS)", title: "LT 0 KC", description: "" },
    LT1: { code: "LT(1,KC_TRNS)", title: "LT 1 KC", description: "" },
    LT2: { code: "LT(2,KC_TRNS)", title: "LT 2 KC", description: "" },
    LT3: { code: "LT(3,KC_TRNS)", title: "LT 3 KC", description: "" },
    LT4: { code: "LT(4,KC_TRNS)", title: "LT 4 KC", description: "" },
    LT5: { code: "LT(5,KC_TRNS)", title: "LT 5 KC", description: "" },
    LT6: { code: "LT(6,KC_TRNS)", title: "LT 6 KC", description: "" },
  };
  modPress: any = {};
  modTap: any = {};
}
